**1)Load the data**

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data_2022.csv')

**2)Look at first rows**

In [3]:
df.head()

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
0,519644808,741961800,559.6,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
1,519644808,741961800,559.6,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
2,504795522,692673877,699.5,0.0,2022-01-27,MBL ITA16BLT004 Regular Casual Tan 34,MENS BELT,Tan,34,East,East_6510,2022
3,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
4,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022

**3)check the size**

In [4]:
df.shape

(2534161, 12)

**4)check the column types**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2534161 entries, 0 to 2534160
Data columns (total 12 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             int64
 1   bill_id             int64
 2   line_item_amount    float64
 3   bill_discount       float64
 4   transaction_date    object
 5   description         object
 6   inventory_category  object
 7   colour              object
 8   size                object
 9   zone_name           object
 10  store_name          object
 11  year                int64
dtypes: float64(2), int64(3), object(7)
memory usage: 232.0+ MB

**5)Count missing values**

In [6]:
df.isnull().sum()

user_id                    0
bill_id                    0
line_item_amount           0
bill_discount              0
transaction_date           0
description                4
inventory_category    208257
colour                 15313
size                   15313
zone_name                  0
store_name                 0
year                       0
dtype: int64

In [7]:
(df.isnull().sum()/len(df)*100).round(2)

user_id               0.00
bill_id               0.00
line_item_amount      0.00
bill_discount         0.00
transaction_date      0.00
description           0.00
inventory_category    8.22
colour                0.60
size                  0.60
zone_name             0.00
store_name            0.00
year                  0.00
dtype: float64

**6)investigate duplicates**

In [8]:
df.duplicated().sum()

np.int64(558608)

**6.a)find sum duplicated rows**

In [9]:
dup_rows=df[df.duplicated(keep=False)]

In [10]:
dup_rows.head(10)

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
0,519644808,741961800,559.6,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
1,519644808,741961800,559.6,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
3,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
4,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
5,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
6,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
7,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
8,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
9,12626591,768369011,519.6,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
10,496507098,779140853,559.6,0.0,2022-11-10,MBL ITS17BLT005 Regular Casual Tan 34,MENS BELT,Tan,34,South,South_6028,2022

**6.b)pick on bill**

In [11]:
df[df['bill_id']==741961800]

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
0,519644808,741961800,559.600,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
1,519644808,741961800,559.600,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
1628833,519644808,741961800,0.001,0.0,2022-04-20,CBG ITCBS00002 NA NA WHITE 8X3X11.5,CBG ITCBS00002 NA NA White 8x3x11.5``,NOT-CAPTURED,NOT-CAPTURED,North,North_6023,2022
1628834,519644808,741961800,0.001,0.0,2022-04-20,CBG ITCBS00002 NA NA WHITE 8X3X11.5,CBG ITCBS00002 NA NA White 8x3x11.5``,NOT-CAPTURED,NOT-CAPTURED,North,North_6023,2022

**7)Check the categories**

In [12]:
df['inventory_category'].value_counts().head(20)

inventory_category
CTrims ITCBM00003 NA NA White ``10x4x14````    278136
CBG ITCBR00001 NA NA White 12x4x16``           109812
SHirts                                          78292
TBG ITPTB00011 NA NA Black 46x25x26             41192
TBG ITPTB00012 NA NA Black 22x7x27              29048
EB GV 500 JAN2022                               26288
TBG ITPTB00007 NA NA Grey (22x15x6)             10011
CBG ITCBS00002 NA NA White 8x3x11.5``            8842
TBG ITPTB00013 NA NA Black 41x21x52              6896
TBG ITPTB00010 NA NA Black (46x24x24)            3771
CARRY BAG                                        2691
TBG ITPTB00008 NA NA Brown (46x23x26)            1667
WOthers ITPMW00003 NA NA Blk+Brown 42MM          1633
MSH ITMSH04357 Slim LS Ecru M                    1172
MSH ITMSH04360 Slim LS White M                   1098
MTR ITMTR00365 Brooklyn FF Stone 34              1092
MTR ITMTR00879 Brooklyn FF Grey 34               1010
TBG ITPTB00009 NA NA Brown (41x21x44)            1009
MSH ITMSH04360 Slim LS Olive M                   1009
MWL ITMWL00038 Solids Solids Brown 23CM          1002
Name: count, dtype: int64

In [13]:
df['inventory_category'].nunique()

39078

**8)Quick look at the numbers and zones**

In [14]:
df['line_item_amount'].describe()

count    2.534161e+06
mean     1.341307e+03
std      9.856585e+02
min      0.000000e+00
25%      6.001548e+02
50%      1.337060e+03
75%      2.051461e+03
max      1.141992e+05
Name: line_item_amount, dtype: float64

In [15]:
df['zone_name'].value_counts()

zone_name
South      1736856
West        273203
North       250430
East        177032
ROOT         83285
Central      13355
Name: count, dtype: int64

**Step A: Make a True/False check for each row**

In [16]:
df['zone_name'] == 'South'

0          False
1          False
2          False
3           True
4           True
           ...
2534156     True
2534157     True
2534158     True
2534159     True
2534160     True
Name: zone_name, Length: 2534161, dtype: bool

**Step B: Use that check as a filter**

In [17]:
df[df['zone_name'] == 'South']

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
3,12626591,768369011,519.6000,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
4,12626591,768369011,519.6000,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
5,12626591,768369011,519.6000,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
6,12626591,768369011,519.6000,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
7,12626591,768369011,519.6000,0.0,2022-10-09,MBL ITA16BLT001 Regular Casual Dark Brown 32,MENS BELT,Dark Brown,32,South,South_6017,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
2534156,505650423,794914516,900.3072,1700.0,2022-12-31,MSH ITMSH04953 Slim LS Rust Mel 4XL,MSH ITMSH04953 Slim LS Rust Mel 4XL,NaN,NaN,South,South_7158,2022
2534157,437272840,794936290,699.0000,0.0,2022-12-31,MRG ITMRG00006 Regular SS Maroon M,MRG ITMRG00006 Regular SS Maroon M,NaN,NaN,South,South_7465,2022
2534158,535386379,795169743,2261.8189,0.0,2022-12-31,MTR ITMTR00726 Brooklyn FF Khaki 32,MTR ITMTR00726 Brooklyn FF Khaki 32,NaN,NaN,South,South_7349,2022
2534159,527164270,795139378,2999.0000,0.0,2022-12-31,MTR ITMTR00726 Brooklyn FF Khaki 32,MTR ITMTR00726 Brooklyn FF Khaki 32,NaN,NaN,South,South_7088,2022
2534160,358264081,795160649,1299.0000,0.0,2022-12-31,MSO ITMSO00402 Regular Shorts Anthra Mel S,MSO ITMSO00402 Regular Shorts Anthra Mel S,NaN,NaN,South,South_7001,2022

**Step C: Look at one column of the filtered rows**

In [18]:
df[df['zone_name'] == 'South']['line_item_amount'].describe()

count    1.736856e+06
mean     1.314864e+03
std      9.337493e+02
min      0.000000e+00
25%      5.505558e+02
50%      1.317552e+03
75%      2.024296e+03
max      2.990640e+04
Name: line_item_amount, dtype: float64

In [19]:
   df['inventory_category'].str.startswith('CBG', na=False)

0          False
1          False
2          False
3          False
4          False
           ...
2534156    False
2534157    False
2534158    False
2534159    False
2534160    False
Name: inventory_category, Length: 2534161, dtype: bool

In [20]:
dups = df[df.duplicated(keep=False)]
dups['line_item_amount'].describe()

count    947573.000000
mean       1266.884178
std        1011.033861
min           0.000000
25%         629.099998
50%        1214.570200
75%        1872.286400
max      114199.200000
Name: line_item_amount, dtype: float64

In [21]:
dups['inventory_category'].value_counts().head(10)

inventory_category
CTrims ITCBM00003 NA NA White ``10x4x14````    77594
CBG ITCBR00001 NA NA White 12x4x16``           32281
SHirts                                         28963
EB GV 500 JAN2022                              22798
TBG ITPTB00011 NA NA Black 46x25x26            14530
TBG ITPTB00012 NA NA Black 22x7x27              6931
TBG ITPTB00007 NA NA Grey (22x15x6)             5986
TBG ITPTB00013 NA NA Black 41x21x52             3879
CBG ITCBS00002 NA NA White 8x3x11.5``           2207
TBG ITPTB00010 NA NA Black (46x24x24)           1511
Name: count, dtype: int64

In [22]:
dups.sort_values('line_item_amount', ascending=False).head(5)

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
2334797,245109959,754971321,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
2334798,245109959,755033270,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
2334796,245109959,754971321,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
2334799,245109959,755033270,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
245992,245109959,755033270,89568.0,0.0,2022-08-23,MSH ITMSH01626 Slim LS White XL,MSH ITMSH01626 Slim LS White XL,White,XL,North,North_7064,2022

In [23]:
sizes = df.groupby(list(df.columns), dropna=False).size()

In [24]:
sizes.value_counts().sort_index()

1     1586588
2      289009
3       67099
4       18831
5        7048
6        3168
7        1406
8         811
9         344
10        385
11         80
12         52
13         77
14        137
15         69
16         20
18          7
19          1
20        170
21         14
22        190
24          5
25          4
27          1
28          7
30          7
32          1
35          1
40         16
44          2
45          1
60          2
Name: count, dtype: int64

In [25]:
dups.sort_values('line_item_amount', ascending=False).head(5)

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
2334797,245109959,754971321,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
2334798,245109959,755033270,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
2334796,245109959,754971321,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
2334799,245109959,755033270,114199.2,0.0,2022-08-23,MSH ITMSH01626 Slim LS White M,MSH ITMSH01626 Slim LS White M,White,M,North,North_7064,2022
245992,245109959,755033270,89568.0,0.0,2022-08-23,MSH ITMSH01626 Slim LS White XL,MSH ITMSH01626 Slim LS White XL,White,XL,North,North_7064,2022

**Task 1: Test my "multiples" claim yourself**

In [26]:
s = df[df['description'] == 'MSH ITMSH04357 Slim LS Sky M']
s['line_item_amount'].value_counts().head(10)

line_item_amount
2999.0000    415
2699.1000     25
2624.0000     18
2499.0000      7
2574.4530      7
2398.9600      7
2414.5515      6
2284.7144      5
2450.2017      5
2099.3000      5
Name: count, dtype: int64

**Task 2: Zero amounts**

In [27]:
df[df['line_item_amount'] == 0]

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
505,504136583,688482993,0.0,2004.0,2022-01-22,MTR ITMTR00254 Brooklyn FF Grey 36,MTR ITMTR00254 Brooklyn FF Grey 36,Grey,36,South,South_7194,2022
10402,501066526,710392038,0.0,2199.0,2022-04-01,MSH ITMSH03154 SLIM LS Amber L,NaN,Amber,L,South,South_7459,2022
13315,504546595,710001303,0.0,1399.0,2022-03-30,MWL ITMWL00032 Regular Bifold Blue 23CM,NaN,Blue,23CM,South,South_7345,2022
13316,504546595,710001303,0.0,1399.0,2022-03-30,MWL ITMWL00032 Regular Bifold Blue 23CM,NaN,Blue,23CM,South,South_7345,2022
13685,295901987,700534170,0.0,399.0,2022-02-27,MBX ITMBX00058 Regular Boxer Navy L,MBX ITMBX00058 Regular Boxer Navy L,NOT-CAPTURED,NOT-CAPTURED,West,West_7251,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
2528908,357396685,768171840,0.0,1999.0,2022-10-08,MTS ITMTS01275 Regular SS Light Blue M,MTS ITMTS01275 Regular SS Light Blue M,NOT-CAPTURED,NOT-CAPTURED,South,South_7489,2022
2529123,349152202,762947459,0.0,649.0,2022-09-20,MBX ITMBX00081 Regular Boxer Navy M,MBX ITMBX00081 Regular Boxer Navy M,NOT-CAPTURED,NOT-CAPTURED,South,South_7259,2022
2530896,527599909,767596581,0.0,649.0,2022-10-06,MBX ITMBX00086 Regular Boxer Navy L,MBX ITMBX00086 Regular Boxer Navy L,NOT-CAPTURED,NOT-CAPTURED,North,North_7243,2022
2530909,482324657,790941057,0.0,3748.0,2022-12-18,MBX ITMBX00086 Regular Boxer Navy L,MBX ITMBX00086 Regular Boxer Navy L,NOT-CAPTURED,NOT-CAPTURED,South,South_7392,2022
2530910,482324657,790941057,0.0,3748.0,2022-12-18,MBX ITMBX00086 Regular Boxer Navy L,MBX ITMBX00086 Regular Boxer Navy L,NOT-CAPTURED,NOT-CAPTURED,South,South_7392,2022

**Task A (find hidden placeholders):**

In [28]:
(df['colour'] == 'NOT-CAPTURED').sum()
(df['size'] == 'NOT-CAPTURED').sum()

np.int64(2106745)

In [29]:
df_clean = df.copy()

In [30]:
df_clean['transaction_date'] = pd.to_datetime(df_clean['transaction_date'])

In [31]:
df_clean['transaction_date'].dtype

dtype('<M8[ns]')

In [32]:
df[df['bill_id'] == 741961800]

,user_id,bill_id,line_item_amount,bill_discount,transaction_date,description,inventory_category,colour,size,zone_name,store_name,year
0,519644808,741961800,559.600,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
1,519644808,741961800,559.600,0.0,2022-04-20,MBL ITA16BLT004 Regular Casual Tan 32,MENS BELT,Tan,32,North,North_6023,2022
1628833,519644808,741961800,0.001,0.0,2022-04-20,CBG ITCBS00002 NA NA WHITE 8X3X11.5,CBG ITCBS00002 NA NA White 8x3x11.5``,NOT-CAPTURED,NOT-CAPTURED,North,North_6023,2022
1628834,519644808,741961800,0.001,0.0,2022-04-20,CBG ITCBS00002 NA NA WHITE 8X3X11.5,CBG ITCBS00002 NA NA White 8x3x11.5``,NOT-CAPTURED,NOT-CAPTURED,North,North_6023,2022

In [33]:
df_clean['month'] = df_clean['transaction_date'].dt.month
df_clean['month'].value_counts().sort_index()

month
1     222717
2     115343
3     157472
4     208777
5     217049
6     217706
7     287341
8     196959
9     166623
10    337411
11    155988
12    250775
Name: count, dtype: int64

In [34]:
df_clean.groupby('month')['line_item_amount'].sum()

month
1     2.592187e+08
2     1.521466e+08
3     2.056403e+08
4     2.804887e+08
5     3.068707e+08
6     2.878929e+08
7     3.429898e+08
8     2.696859e+08
9     2.307127e+08
10    4.847604e+08
11    2.323900e+08
12    3.462905e+08
Name: line_item_amount, dtype: float64

In [35]:
df_clean.groupby('month')['line_item_amount'].agg(['sum', 'count', 'mean'])

                sum   count         mean
month
1      2.592187e+08  222717  1163.892918
2      1.521466e+08  115343  1319.079597
3      2.056403e+08  157472  1305.884641
4      2.804887e+08  208777  1343.484875
5      3.068707e+08  217049  1413.831455
6      2.878929e+08  217706  1322.392872
7      3.429898e+08  287341  1193.668261
8      2.696859e+08  196959  1369.248694
9      2.307127e+08  166623  1384.639233
10     4.847604e+08  337411  1436.706095
11     2.323900e+08  155988  1489.794081
12     3.462905e+08  250775  1380.881142

**Count starting numbers**

In [36]:
   (df_clean['colour'] == 'NOT-CAPTURED').sum()
   (df_clean['size'] == 'NOT-CAPTURED').sum()

np.int64(2106745)

**Replace the text with a real missing value**

In [37]:
df_clean.isnull().sum()

user_id                    0
bill_id                    0
line_item_amount           0
bill_discount              0
transaction_date           0
description                4
inventory_category    208257
colour                 15313
size                   15313
zone_name                  0
store_name                 0
year                       0
month                      0
dtype: int64

In [38]:
df_clean.shape

(2534161, 13)

In [39]:
# Does NOT change anything (result is thrown away)
df_clean['colour'].replace('NOT-CAPTURED', pd.NA)

# Changes the column (result is saved back)
df_clean['colour'] = df_clean['colour'].replace('NOT-CAPTURED', pd.NA)

In [40]:
df_clean['colour'] = df_clean['colour'].replace('NOT-CAPTURED', pd.NA)

In [41]:
   df_clean.isnull().sum()

user_id                     0
bill_id                     0
line_item_amount            0
bill_discount               0
transaction_date            0
description                 4
inventory_category     208257
colour                2122057
size                    15313
zone_name                   0
store_name                  0
year                        0
month                       0
dtype: int64

In [42]:
df_clean.shape

(2534161, 13)

In [43]:
df_clean['size'] = df_clean['size'].replace('NOT-CAPTURED', pd.NA)

In [44]:
df_clean.isnull().sum()

user_id                     0
bill_id                     0
line_item_amount            0
bill_discount               0
transaction_date            0
description                 4
inventory_category     208257
colour                2122057
size                  2122058
zone_name                   0
store_name                  0
year                        0
month                       0
dtype: int64

**Create the new column**

In [45]:
df_clean['type_code'] = df_clean['description'].str.split().str[0].str.upper()

**How many codes now?**

In [46]:
df_clean['type_code'].nunique()

94

**The biggest ones**

In [47]:
df_clean['type_code'].value_counts().head(15)

type_code
MSH       846856
MTR       362136
CTRIMS    278136
MTS       190040
MDE       160351
CBG       121345
TBG        94335
SHIRTS     72890
BSH        54771
MSS        41861
BTS        38181
MSO        30495
EB         26288
MBX        23998
BDE        22391
Name: count, dtype: int64

**Check that your code matches reality**

In [48]:
df_clean[df_clean['type_code'] == 'MTS'][['description', 'inventory_category']].head(10)

,description,inventory_category
690,MTS ITMTS00388 Regular SS Dk Fuchsia S,MTS ITMTS00388 Regular SS Dk Fuchsia S
1487,MTS ITMTS00538 Regular SS Black L,MTS ITMTS00538 Regular SS Black L
1623,MTS ITMTS00496 Regular SS Cobalt M,MTS ITMTS00496 Regular SS Cobalt M
1624,MTS ITMTS00496 Regular SS Cobalt M,MTS ITMTS00496 Regular SS Cobalt M
1625,MTS ITMTS00496 Regular SS Cobalt M,MTS ITMTS00496 Regular SS Cobalt M
1626,MTS ITMTS00496 Regular SS Cobalt M,MTS ITMTS00496 Regular SS Cobalt M
1627,MTS ITMTS00496 Regular SS Cobalt M,MTS ITMTS00496 Regular SS Cobalt M
1649,MTS ITMTS00546 Regular SS Olive S,MTS ITMTS00546 Regular SS Olive S
1665,MTS ITMTS00470 Stretch SS Grey Mel XL,MTS ITMTS00470 Stretch SS Grey Mel XL
1666,MTS ITMTS00470 Stretch SS Grey Mel XL,MTS ITMTS00470 Stretch SS Grey Mel XL

**Make sure no rows were lost**

In [49]:
df_clean.shape

(2534161, 14)

**Flag the tiny rows**

In [50]:
df_clean['is_tiny'] = df_clean['line_item_amount'] < 10

**What share of each type code is tiny?**

In [51]:
share = df_clean.groupby('type_code')['is_tiny'].mean().sort_values(ascending=False)
share.head(12).round(2)

type_code
EB         1.00
COTHERS    1.00
DEFAULT    1.00
EARN       1.00
CTRIMS     1.00
CBG        0.91
BCP        0.80
ASH        0.17
LBG        0.16
TBG        0.11
KHAKI      0.10
REUNION    0.05
Name: is_tiny, dtype: float64

**How many tiny rows exist overall?**

In [52]:
df_clean['is_tiny'].sum()

np.int64(428429)

**Check the shape**

In [53]:
df_clean.shape

(2534161, 15)

**Step 3 final: create the flag**

In [54]:
non_merch_codes = ['EB', 'COTHERS', 'DEFAULT', 'EARN', 'CTRIMS', 'CBG', 'BCP']

In [55]:
df_clean['is_non_merch'] = df_clean['type_code'].isin(non_merch_codes)

In [56]:
df_clean['is_non_merch'].sum()

np.int64(426251)

In [57]:
df_clean.groupby('is_non_merch')['line_item_amount'].agg(['count', 'sum', 'mean']).round(0)

                count           sum    mean
is_non_merch
False         2107910  3.398583e+09  1612.0
True           426251  5.044060e+05     1.0

In [58]:
df_clean.shape

(2534161, 16)

In [59]:
orig_cols = ['user_id', 'bill_id', 'line_item_amount', 'bill_discount', 'transaction_date', 'description', 'inventory_category', 'colour', 'size', 'zone_name', 'store_name', 'year']

In [60]:
df_clean['is_repeat_row'] = df_clean.duplicated(subset=orig_cols)

In [61]:
df_clean['is_repeat_row'].sum()

np.int64(558725)

In [62]:
df_clean[~df_clean['is_non_merch']].groupby('zone_name')['is_repeat_row'].mean().round(3)

zone_name
Central    0.196
East       0.150
North      0.177
ROOT       0.210
South      0.245
West       0.211
Name: is_repeat_row, dtype: float64

In [63]:
df_clean.shape

(2534161, 17)

In [64]:
df_clean[~df_clean['is_non_merch']]['is_repeat_row'].sum()

np.int64(477294)

In [65]:
df_clean['bill_total'] = df_clean.groupby('bill_id')['line_item_amount'].transform('sum')

In [66]:
df_clean.drop_duplicates('bill_id')['bill_total'].quantile([0.5, 0.9, 0.99, 0.999]).round(0)

0.500     4498.0
0.900    12594.0
0.990    33184.0
0.999    68667.0
Name: bill_total, dtype: float64

In [67]:
df_clean.shape

(2534161, 18)

In [68]:
bulk_threshold = df_clean.drop_duplicates('bill_id')['bill_total'].quantile(0.99)
bulk_threshold

np.float64(33184.00023599999)

In [69]:
df_clean['is_bulk_bill'] = df_clean['bill_total'] > bulk_threshold

In [70]:
df_clean['is_bulk_bill'].sum()

np.int64(171573)

In [71]:
df_clean.groupby('is_bulk_bill')['line_item_amount'].agg(['count', 'sum']).round(0)

                count           sum
is_bulk_bill
False         2362588  3.110864e+09
True           171573  2.882228e+08

In [72]:
df_clean.shape

(2534161, 19)

**Confirm "one discount per bill" (expected: 1)**

In [73]:
df_clean.groupby('bill_id')['bill_discount'].nunique().max()

1

**The wrong total vs the right total (two separate cells)**

In [74]:
df_clean['bill_discount'].sum()

np.float64(334590952.3649)

**Create the safe discount column**

In [75]:
df_clean['discount_once'] = df_clean['bill_discount'].where(~df_clean.duplicated('bill_id'), 0)

**Check it**

In [76]:
df_clean.shape

(2534161, 20)

In [77]:
df_clean.drop_duplicates('bill_id')['bill_discount'].sum()

np.float64(81760185.08714001)

In [78]:
df_clean['discount_once'].sum()

np.float64(81760185.08714)

**Turn the True/False flags into 1/0**

In [79]:
flag_cols = ['is_tiny', 'is_non_merch', 'is_repeat_row', 'is_bulk_bill']

In [80]:
df_clean[flag_cols] = df_clean[flag_cols].astype(int)

**Check the flags still add up**

In [81]:
df_clean[flag_cols].sum()

is_tiny          428429
is_non_merch     426251
is_repeat_row    558725
is_bulk_bill     171573
dtype: int64

**Final missing-values check**

In [84]:
df_clean.isnull().sum()

user_id                     0
bill_id                     0
line_item_amount            0
bill_discount               0
transaction_date            0
description                 4
inventory_category     208257
colour                2122057
size                  2122058
zone_name                   0
store_name                  0
year                        0
month                       0
type_code                   4
is_tiny                     0
is_non_merch                0
is_repeat_row               0
bill_total                  0
is_bulk_bill                0
discount_once               0
dtype: int64

**Final shape (expected (2534161, 20))**

In [85]:
df_clean.shape

(2534161, 20)

**Export the clean file**

In [88]:
df_clean.to_csv('zudio_sales_clean_2022.csv', index=False)

In [89]:
import os
os.path.abspath('zudio_sales_clean_2022.csv')

'C:\\Users\\hagek\\zudio_sales_clean_2022.csv'

In [90]:
os.path.exists('zudio_sales_clean_2022.csv')

True

In [91]:
df_clean.to_csv('zudio_sales_clean_2022.csv', index=False)

In [92]:
df_clean.head(10000).to_csv('test_10k.csv', index=False)

**Split the data**

In [93]:
chunk = 520000
for i, start in enumerate(range(0, len(df_clean), chunk), start=1):
    df_clean.iloc[start:start + chunk].to_csv(f'sales_part{i}.csv', index=False)

In [94]:
import os
[f for f in os.listdir('.') if f.startswith('sales_part')]

['sales_part1.csv',
 'sales_part2.csv',
 'sales_part3.csv',
 'sales_part4.csv',
 'sales_part5.csv']

In [95]:
  chunk = 520000
  for i, start in enumerate(range(0, len(df_clean), chunk), start=1):
      df_clean.iloc[start:start + chunk].to_csv(f'sales_part{i}.csv', index=False)

In [96]:
   os.getcwd()

'C:\\Users\\hagek'

In [97]:
import os
[f for f in os.listdir('.') if f.startswith('sales_part')]

['sales_part1.csv',
 'sales_part2.csv',
 'sales_part3.csv',
 'sales_part4.csv',
 'sales_part5.csv']

In [98]:
   os.getcwd()

'C:\\Users\\hagek'